# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:5000/mykube-img
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort #ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  
  annotations: 
   nginx.ingress.kubernetes.io/rewrite-target: /

  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

